version: '3.8'

services:
  patientsapi:
    image: ${DOCKER_REGISTRY-}patientsapi
    build:
      context: ./PatientsAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=patient-sqlserver;Database=PatientsDB;User Id=sa;Password=Password123!;MultipleActiveResultSets=true;TrustServerCertificate=True;
    depends_on:
      - patient-sqlserver
    networks:
      - commonnetwork

  patient-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: patient-sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
    volumes:
      - sqlvolume:/data/db
    networks:
      - commonnetwork

  notesapi:
    image: ${DOCKER_REGISTRY-}notesapi
    build:
      context: ./NotesAPI
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5002
      - ConnectionStrings__MongoDB=mongodb://mongodb-notes:27017
      - MongoDB__DatabaseName=NotesDB
    depends_on:
      - mongodb-notes
    networks:
      - commonnetwork

  mongodb-notes:
    image: mongo:latest
    container_name: MongoDb_NotesAPI
    ports:
      - "27017:27017"
    volumes:
      - mongovolume:/data/db
    networks:
      - commonnetwork

  identity:
    image: ${DOCKER_REGISTRY-}identity
    container_name: IdentityAPI
    build:
      context: .
      dockerfile: Identity/Dockerfile
    ports:
      - "5004:5004"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5004
      - ConnectionStrings__DefaultConnection=Server=user-sqlserver;Database=UserDB;User Id=sa;Password=Password123!;MultipleActiveResultSets=true;TrustServerCertificate=True;
    depends_on:
      - user-sqlserver
    networks:
      - commonnetwork

  user-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: user-sqlserver
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
    volumes:
      - sqlidentityvolume:/data/db
    networks:
      - commonnetwork

  diabeticassessmentapi:
    image: ${DOCKER_REGISTRY-}diabeticassessmentapi
    build:
      context: ./DiabeticAssessmentAPI
      dockerfile: Dockerfile
    ports:
      - "5006:5006"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5006
      - ServiceUrl__PatientAPI=http://patientsapi:5000
      - ServiceUrl__NoteAPI=http://notesapi:5002
    depends_on:
      - patientsapi
      - notesapi
    networks:
      - commonnetwork

networks:
  commonnetwork:
    driver: bridge

volumes:
  sqlvolume:
  mongovolume:
  sqlidentityvolume:
