version: '3.8'

services:
  patientsapi:
    image: ${DOCKER_REGISTRY-}patientsapi
    build:
      context: ./PatientsAPI
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=patient-sqlserver;Database=PatientsDB;User Id=sa;Password=Password123!;MultipleActiveResultSets=true;TrustServerCertificate=True;
    depends_on:
      - patient-sqlserver  
    networks:
      - commomnetwork

  patient-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: patient-sqlserver
    ports:
      - "1433:1433" 
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
    volumes:
      - sqlvolume:/data/db
    networks:
      - commomnetwork

  notesapi:
      image: ${DOCKER_REGISTRY-}notesapi
      container_name: NotesApi
      build:
        context: ./NotesAPI
        dockerfile: Dockerfile
      ports:
        - "5002:5002" 
        - "5003:5003"
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ConnectionStrings__MongoDB=mongodb://mongodb-notes:27017
        - MongoDB__DatabaseName=NotesDB
      depends_on:
        - mongodb-notes 
      networks:
        - commomnetwork

  mongodb-notes:
    image: mongo:latest
    container_name: MongoDb_NotesAPI
    ports:
      - "27017:27017" 
    volumes:
      - mongovolume:/data/db
    networks:
      - commomnetwork

  identity:
    image: ${DOCKER_REGISTRY-}identity
    container_name: IdentityAPI
    build:
      context: .
      dockerfile: Identity/Dockerfile
    ports:
      - "5004:5004" 
      - "5005:5005"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=user-sqlserver;Database=UserDB;User Id=sa;Password=Password123!;MultipleActiveResultSets=true;TrustServerCertificate=True;
    depends_on:
      - user-sqlserver  
    networks:
      - commomnetwork


  user-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: user-sqlserver
    ports:
      - "1434:1433" 
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"
    volumes:
      - sqlidentityvolume:/data/db
    networks:
      - commomnetwork

networks:
  commomnetwork:
    driver: bridge

  
volumes:
  sqlvolume:   
  mongovolume:
  sqlidentityvolume:


